vim9script

# plugins
source ~/.vim/config/plugins.vim

# variables
source ~/.vim/config/variables.vim

# options
source ~/.vim/config/options.vim

# coc.nvim
colorscheme dark-colorscheme

# terminal
source ~/.vim/config/terminal.vim

# mappings
source ~/.vim/config/mappings.vim
