call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

set number
set relativenumber
set clipboard=unnamedplus
set virtualedit=all
set textwidth=0
set formatoptions-=t   
set nowrap
set sidescrolloff=9999
set scrolloff=9999
set background=dark
set cursorline

" coc.nvim
colorscheme wildcharm
let g:coc_global_extensions = ['coc-clangd']
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gf <Plug>(coc-format)
