
# Start windows at index 1 instead of 0
set -g base-index 1

# Start panes at index 1 instead of 0
set -g pane-base-index 1

# Automatically renumber windows when one is closed, to avoid gaps
set -g renumber-windows on
