#  _                      _            _
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   <
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|

$accent = rgb(cba6f7)
$accentAlpha = cba6f7
$font = JetBrains Mono Nerd Font

# GENERAL
general {
    disable_loading = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 2
    color = rgb(1e1e2e)
}

# TIME
label {
    monitor =
    text = $TIME
    color = $accent
    font_size = 90
    font_family = $font
    position = 0, -150
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $accent
    font_size = 25
    font_family = $font
    position = 0, -300
    halign = center
    valign = top
}

# USER AVATAR
image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $accent
    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <span foreground="##$accentAlpha"><i>󰌾 Logged in as </i><span weight="bold">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = rgb(f38ba8)
    capslock_color = rgb(fab387)
    position = 0, -45
    halign = center
    valign = center
}
