[window]
padding = { x = 8, y = 8}

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
bold = { family = "JetBrainsMono Nerd Font Mono" }
italic = { family = "JetBrainsMono Nerd Font Mono" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono"}

[keyboard]
bindings = [
  { key = "J", mods = "Control", action = "ScrollLineDown" },
  { key = "K", mods = "Control", action = "ScrollLineUp" },
]

[colors.primary]
background = "#121212"
foreground = "#cdd6f4"

[colors.normal]
black = "#121212"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#89dceb"
white = "#cdd6f4"

[colors.bright]
black = "#6c7086"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#89dceb"
white = "#cdd6f4"

[colors.selection]
text = "CellForeground"
background = "#313244"

[colors.cursor]
text = "CellBackground"
cursor = "#fab387"
