[window]
padding = { x = 8, y = 8}

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
bold = { family = "JetBrainsMono Nerd Font Mono" }
italic = { family = "JetBrainsMono Nerd Font Mono" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono"}

[keyboard]
bindings = [
  { key = "J", mods = "Control", action = "ScrollLineDown" },
  { key = "K", mods = "Control", action = "ScrollLineUp" },
]

[colors.primary]
background = "#1c1c1c"
foreground = "#bcbcbc"

[colors.normal]
black = "#1c1c1c"
red = "#d75f5f"
green = "#87af87"
yellow = "#afaf87"
blue = "#87afd7"
magenta = "#af87af"
cyan = "#87afaf"
white = "#bcbcbc"

[colors.bright]
black = "#767676"
red = "#d75f5f"
green = "#87af87"
yellow = "#afaf87"
blue = "#87afd7"
magenta = "#af87af"
cyan = "#87afaf"
white = "#bcbcbc"

[colors.selection]
text = "CellForeground"
background = "#303030"

[colors.cursor]
text = "CellBackground"
cursor = "#afaf87"
